# Generated by Django 5.0.6 on 2026-05-18 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True)),
                ('number1', models.IntegerField()),
                ('number2', models.IntegerField()),
                ('number3', models.IntegerField()),
                ('number4', models.IntegerField()),
                ('number5', models.IntegerField()),
                ('number6', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('number1', models.IntegerField()),
                ('number2', models.IntegerField()),
                ('number3', models.IntegerField()),
                ('number4', models.IntegerField()),
                ('number5', models.IntegerField()),
                ('number6', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
